Task_1_1_3
YuliaVyaznikova/OOP pull request #7
Opened 2024-10-11 05:51 UTC by YuliaVyaznikova

2024-10-12 05:16 UTC, vlitomsk requested changes

2024-10-12 05:16 UTC, vlitomsk commented on Task_1_1_3/src/main/java/ru/nsu/vyaznikova/Variable.java
> +        return 0;
А если с нужным именем в assignments не нашлось, возвращает 0? Как тогда отличить результат "0" успешный от результата "0" проблемного? Предлагаю выбросить исключение в таком случае.

2024-10-12 11:49 UTC, YuliaVyaznikova commented on Task_1_1_3/src/main/java/ru/nsu/vyaznikova/Variable.java
> +        return 0;
Добавила исключение

2024-10-18 05:31 UTC, vlitomsk approved these changes

2024-10-18 05:31 UTC, merged